//Slider types
export const CHANGE_NUM_PROJECT_SLIDER = 'CHANGE_NUM_PROJECT_SLIDER';
export const CHANGE_PROJECTS_ARRAY = 'CHANGE_PROJECTS_ARRAY';
export const CHANGE_STUDENTS_ARRAY = 'CHANGE_STUDENT_ARRAY';
