//Slider types
export const CHANGE_NUM_PROJECT_SLIDER = 'CHANGE_NUM_PROJECT_SLIDER';
export const CHANGE_PROJECTS_ARRAY = 'CHANGE_PROJECTS_ARRAY';
export const CHANGE_STUDENTS_ARRAY = 'CHANGE_STUDENT_ARRAY';
export const ASSIGN_PROJ_TO_STUDENT = 'ASSIGN_PROJ_TO_STUDENT';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const SET_MAX_POSSIBLE_CHOICES = 'SET_MAX_POSSIBLE_CHOICES';
